services:
  kobodevcontainer:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: KoboToolchain
    user: "${UID}:${GID}"
    #user: "kobodev"
    ports:
      - "2222:2345" # Host port 2222 -> container port 2345
    command: >
      sh -c "
        echo [LOG][kobodevcontainer] Start command, stats, sshd
        whoami
        id
        /usr/sbin/sshd -f /home/kobodev/sshd_config
        echo [LOG][kobodevcontainer] bash
        exec bash
      "
    working_dir: /home/kobodev/
    tty: true
